### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cjse** [torquebox/torquespec#9]
Hi,

it looks like this project doesn't have a license yet. That is currently preventing us from using it.

If you need help choosing a license, check out http://choosealicense.com.

**Comment by jcrossley3** [comment]
Do you have a particular preference?

**Comment by cjse** [comment]
The MIT License (http://choosealicense.com/licenses/mit/) is a common, simple license.

**Comment by jcrossley3** [comment]
Does ASLv2 work for you?

**Comment by cjse** [comment]
Sure!

**Comment by cjse** [comment]
Thanks!
